## Step 1: Load the Sequence Database 

In [22]:
import os
print(os.getcwd())

/Users/mczeneszew/Desktop/FLIPv3/helpers


In [23]:
import pandas as pd
from sequence_database import SequenceDatabase, read_csv_to_sequencedatabase

csv_path = 'four_mutations_small.csv'
seq_db = read_csv_to_sequencedatabase(csv_path)

print("Loaded sequence database:")
display(seq_db.to_dataframe())

Loaded sequence database:


sequence    target  \
0  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  1.000000   
1  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.061910   
2  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.242237   
3  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.006472   
4  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.032719   
5  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.377101   
6  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.008298   
7  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.026480   
8  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  1.445905   
9  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.020161   

                                         annotations  
0  {'Variants': 'VDGV', 'HD': 0, 'Count input': 9...  
1  {'Variants': 'ADGV', 'HD': 1, 'Count input': 3...  
2  {'Variants': 'CDGV', 'HD': 1, 'Count input': 8...  
3  {'Variants': 'DDGV', 'HD': 1, 'Count input': 6...  
4  {'Variants': 'EDGV', 'HD': 1, 'Count input': 8...  
5  {'Variants': 'FDGV', 'HD': 1, 'Count input': 1...  
6  {'Variants': 'GDGV', 'HD': 1, 'Count input': 8...  
7  {'Variants': 'HDGV', 'HD': 1, 'Count input': 4...  
8  {'Variants': 'IDGV', 'HD': 1, 'Count input': 4...  
9  {'Variants': 'KDGV', 'HD': 1, 'Count input': 2...

In [24]:
print("Type of seq_db.sequences:", type(seq_db.sequences))
print("First sequence in seq_db.sequences:", seq_db.sequences[0])
print("Type of first sequence:", type(seq_db.sequences[0]))

Type of seq_db.sequences: <class 'list'>
First sequence in seq_db.sequences: [[-1. -1. -2. ... -1. -1.  1.]
 [-1.  1.  0. ... -2. -1. -2.]
 [-2. -2. -2. ...  2.  7. -1.]
 ...
 [-2.  0.  1. ... -2.  2. -3.]
 [-2.  0.  1. ... -2.  2. -3.]
 [-2.  0.  1. ... -2.  2. -3.]]
Type of first sequence: <class 'numpy.ndarray'>


In [25]:
print("Encoded sequences (BLOSUM62):")
display(seq_db.sequences)

Encoded sequences (BLOSUM62):


[array([[-1., -1., -2., ..., -1., -1.,  1.],
        [-1.,  1.,  0., ..., -2., -1., -2.],
        [-2., -2., -2., ...,  2.,  7., -1.],
        ...,
        [-2.,  0.,  1., ..., -2.,  2., -3.],
        [-2.,  0.,  1., ..., -2.,  2., -3.],
        [-2.,  0.,  1., ..., -2.,  2., -3.]]),
 array([[-1., -1., -2., ..., -1., -1.,  1.],
        [-1.,  1.,  0., ..., -2., -1., -2.],
        [-2., -2., -2., ...,  2.,  7., -1.],
        ...,
        [-2.,  0.,  1., ..., -2.,  2., -3.],
        [-2.,  0.,  1., ..., -2.,  2., -3.],
        [-2.,  0.,  1., ..., -2.,  2., -3.]]),
 array([[-1., -1., -2., ..., -1., -1.,  1.],
        [-1.,  1.,  0., ..., -2., -1., -2.],
        [-2., -2., -2., ...,  2.,  7., -1.],
        ...,
        [-2.,  0.,  1., ..., -2.,  2., -3.],
        [-2.,  0.,  1., ..., -2.,  2., -3.],
        [-2.,  0.,  1., ..., -2.,  2., -3.]]),
 array([[-1., -1., -2., ..., -1., -1.,  1.],
        [-1.,  1.,  0., ..., -2., -1., -2.],
        [-2., -2., -2., ...,  2.,  7., -1.],
        ..

In [26]:
print("Targets:")
display(seq_db.targets)

Targets:


[1.0,
 0.0619096557142,
 0.242237277886,
 0.00647208961971,
 0.0327191845926,
 0.377100728425,
 0.00829790573568,
 0.0264798489707,
 1.4459050863,
 0.0201606557734]

In [27]:
print("Annotations:")
display(seq_db.annotations)

Annotations:


[{'Variants': 'VDGV',
  'HD': 0,
  'Count input': 92735,
  'Count selected': 338346,
  'keep': True,
  'one_vs_rest': 'train',
  'one_vs_rest_validation': nan,
  'two_vs_rest': 'train',
  'two_vs_rest_validation': nan,
  'three_vs_rest': 'train',
  'three_vs_rest_validation': nan,
  'sampled': 'train',
  'sampled_validation': nan,
  'low_vs_high': 'test',
  'low_vs_high_validation': nan},
 {'Variants': 'ADGV',
  'HD': 1,
  'Count input': 34,
  'Count selected': 43,
  'keep': False,
  'one_vs_rest': nan,
  'one_vs_rest_validation': nan,
  'two_vs_rest': nan,
  'two_vs_rest_validation': nan,
  'three_vs_rest': nan,
  'three_vs_rest_validation': nan,
  'sampled': nan,
  'sampled_validation': nan,
  'low_vs_high': nan,
  'low_vs_high_validation': nan},
 {'Variants': 'CDGV',
  'HD': 1,
  'Count input': 850,
  'Count selected': 641,
  'keep': False,
  'one_vs_rest': nan,
  'one_vs_rest_validation': nan,
  'two_vs_rest': nan,
  'two_vs_rest_validation': nan,
  'three_vs_rest': nan,
  'three_v

## Step 2: Create Dataloader  

In [28]:
import pandas as pd
from sequence_database import SequenceDatabase, read_csv_to_sequencedatabase
from dataloader import create_dataloader, ProteinDataset
import numpy as np

protein_dataset = ProteinDataset(seq_db)
print(f"Length of ProteinDataset: {len(protein_dataset)}")
print(f"First item in ProteinDataset: {protein_dataset[0]}")

batch_size = 32

# Creating the DataLoader
dataloader = create_dataloader(protein_dataset, batch_size=batch_size)

print("Created DataLoader:")
# for inputs, labels in dataloader:
#     display(inputs, labels)
for inputs, lengths, labels in dataloader:
    print(inputs.shape, lengths, labels)
    break  # Only printing the first batch 



Length of ProteinDataset: 10
First item in ProteinDataset: (array([[-1., -1., -2., ..., -1., -1.,  1.],
       [-1.,  1.,  0., ..., -2., -1., -2.],
       [-2., -2., -2., ...,  2.,  7., -1.],
       ...,
       [-2.,  0.,  1., ..., -2.,  2., -3.],
       [-2.,  0.,  1., ..., -2.,  2., -3.],
       [-2.,  0.,  1., ..., -2.,  2., -3.]]), 1.0)
Created DataLoader:
torch.Size([10, 265, 20]) tensor([265, 265, 265, 265, 265, 265, 265, 265, 265, 265]) tensor([0.0202, 0.0327, 0.2422, 1.4459, 0.0083, 0.0265, 0.0619, 0.3771, 1.0000,
        0.0065])


## Step 4: Train the CNN Model 

In [29]:
import torch
import torch.nn as nn
import torch.optim as optim
from models_flip import ConvNet

input_size = protein_dataset[0][0].shape[0]  
sequence_length = protein_dataset[0][0].shape[1]  # Getting the sequence length from data 

cnn_model = ConvNet(input_size=input_size, sequence_length=sequence_length)

# Defining loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(cnn_model.parameters(), lr=0.001)

# Now, we can train the model
cnn_model.train()
for epoch in range(10):  # Setting number of epochs 
    for inputs, lengths, labels in dataloader:
        inputs = torch.tensor(inputs, dtype=torch.float32)
        lengths = torch.tensor(lengths, dtype=torch.float32)
        labels = torch.tensor(labels, dtype=torch.float32)
        print("Input shape:", inputs.shape)  # Debug print

        optimizer.zero_grad()
        outputs = cnn_model(inputs, lengths)
        loss = criterion(outputs, labels.unsqueeze(1))  # Ensuring labels match output shape
        loss.backward()
        optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

print("Training complete.")

Input shape: torch.Size([10, 265, 20])
Epoch 1, Loss: 0.31568026542663574
Input shape: torch.Size([10, 265, 20])
Epoch 2, Loss: 4.036042213439941
Input shape: torch.Size([10, 265, 20])
Epoch 3, Loss: 0.26327812671661377
Input shape: torch.Size([10, 265, 20])
Epoch 4, Loss: 0.4347633421421051
Input shape: torch.Size([10, 265, 20])
Epoch 5, Loss: 0.38021132349967957
Input shape: torch.Size([10, 265, 20])
Epoch 6, Loss: 0.259596049785614
Input shape: torch.Size([10, 265, 20])
Epoch 7, Loss: 0.22967281937599182
Input shape: torch.Size([10, 265, 20])
Epoch 8, Loss: 0.27046653628349304
Input shape: torch.Size([10, 265, 20])
Epoch 9, Loss: 0.24053482711315155
Input shape: torch.Size([10, 265, 20])
Epoch 10, Loss: 0.22196345031261444
Training complete.


/var/folders/_q/32dn15tx2w90m2l4r4vkjcpc0000gp/T/ipykernel_76106/2751428894.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs = torch.tensor(inputs, dtype=torch.float32)
/var/folders/_q/32dn15tx2w90m2l4r4vkjcpc0000gp/T/ipykernel_76106/2751428894.py:20: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  lengths = torch.tensor(lengths, dtype=torch.float32)
/var/folders/_q/32dn15tx2w90m2l4r4vkjcpc0000gp/T/ipykernel_76106/2751428894.py:21: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels, dtype=torch.float32)


## Step 4.5: Training the CNN model on sequences of different lengths   

In [40]:
import pandas as pd
from sequence_database import SequenceDatabase, read_csv_to_sequencedatabase

csv_path = 'four_mutations_random_lengths.csv'
seq_db = read_csv_to_sequencedatabase(csv_path)

print("Loaded sequence database:")
display(seq_db.to_dataframe())

Loaded sequence database:


sequence    target  \
0  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  1.000000   
1  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.061910   
2  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.242237   
3  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.006472   
4  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.032719   
5  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.377101   
6  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.008298   
7  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.026480   
8  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  1.445905   
9  [[-1.0, -1.0, -2.0, -3.0, -1.0, 0.0, -2.0, -3....  0.020161   

                                         annotations  
0  {'Variants': 'VDGV', 'HD': 0, 'Count input': 9...  
1  {'Variants': 'ADGV', 'HD': 1, 'Count input': 3...  
2  {'Variants': 'CDGV', 'HD': 1, 'Count input': 8...  
3  {'Variants': 'DDGV', 'HD': 1, 'Count input': 6...  
4  {'Variants': 'EDGV', 'HD': 1, 'Count input': 8...  
5  {'Variants': 'FDGV', 'HD': 1, 'Count input': 1...  
6  {'Variants': 'GDGV', 'HD': 1, 'Count input': 8...  
7  {'Variants': 'HDGV', 'HD': 1, 'Count input': 4...  
8  {'Variants': 'IDGV', 'HD': 1, 'Count input': 4...  
9  {'Variants': 'KDGV', 'HD': 1, 'Count input': 2...

In [41]:
import pandas as pd
from sequence_database import SequenceDatabase, read_csv_to_sequencedatabase
from dataloader import create_dataloader, ProteinDataset
import numpy as np

protein_dataset = ProteinDataset(seq_db)
print(f"Length of ProteinDataset: {len(protein_dataset)}")
print(f"First item in ProteinDataset: {protein_dataset[0]}")

batch_size = 32

# Creating the DataLoader
dataloader = create_dataloader(protein_dataset, batch_size=batch_size)

print("Created DataLoader:")
# for inputs, labels in dataloader:
#     display(inputs, labels)
for inputs, lengths, labels in dataloader:
    print(inputs.shape, lengths, labels)
    break  # Only printing the first batch 

Length of ProteinDataset: 10
First item in ProteinDataset: (array([[-1., -1., -2., ..., -1., -1.,  1.],
       [-1.,  1.,  0., ..., -2., -1., -2.],
       [-2., -2., -2., ...,  2.,  7., -1.],
       ...,
       [-2.,  0.,  1., ..., -2.,  2., -3.],
       [-2.,  0.,  1., ..., -2.,  2., -3.],
       [-2.,  0.,  1., ..., -2.,  2., -3.]]), 1.0)
Created DataLoader:
torch.Size([10, 264, 20]) tensor([264, 264, 264, 264, 264, 264, 264, 264, 264, 264]) tensor([0.0265, 0.0327, 0.0202, 0.0065, 1.0000, 0.0619, 0.0083, 0.2422, 1.4459,
        0.3771])


In [43]:
import torch
import torch.nn as nn
import torch.optim as optim
from models_flip import ConvNet

input_size = protein_dataset[0][0].shape[1]  # Number of features per amino acid
sequence_length = max([len(seq) for seq in seq_db.sequences])  # Maximum sequence length in the dataset
cnn_model = ConvNet(input_size=input_size, sequence_length=sequence_length)

# Defining the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(cnn_model.parameters(), lr=0.001)

# Training the model
cnn_model.train()
# for epoch in range(10):  # Setting number of epochs
#     for inputs, lengths, labels in dataloader:
#         inputs = inputs.float().transpose(1, 2) 
#         labels = labels.float().unsqueeze(1)  

#         optimizer.zero_grad()
#         outputs = cnn_model(inputs, lengths)
#         loss = criterion(outputs, labels)
#         loss.backward()
#         optimizer.step()
#     print(f'Epoch {epoch+1}, Loss: {loss.item()}')
num_epochs = 10
for epoch in range(num_epochs):  # Iterate through a fixed number of epochs
    epoch_loss = 0.0  # To accumulate the loss over an epoch
    
    for inputs, lengths, labels in dataloader:
        # Convert inputs to float32 and transpose to shape (batch_size, channels, sequence_length)
        inputs = inputs.float().transpose(1, 2)
        
        # Convert labels to float32 and add an extra dimension to match the model's output shape
        labels = labels.float().unsqueeze(1)

        # Zero the parameter gradients
        optimizer.zero_grad()

        # Forward pass: compute the model output
        outputs = cnn_model(inputs, lengths)

        # Compute the loss between the model output and the true labels
        loss = criterion(outputs, labels)

        # Backward pass: compute gradient of the loss with respect to model parameters
        loss.backward()

        # Update model parameters
        optimizer.step()

        # Accumulate the loss for the current batch
        epoch_loss += loss.item()
    
    # Print the average loss for the current epoch
    average_loss = epoch_loss / len(dataloader)
    print(f'Epoch {epoch+1}/{num_epochs}, Loss: {average_loss}')


print("Training complete.")

Epoch 1, Loss: 0.3422932028770447
Epoch 2, Loss: 255.3261260986328
Epoch 3, Loss: 0.3548205494880676
Epoch 4, Loss: 11.793645858764648
Epoch 5, Loss: 11.287260055541992
Epoch 6, Loss: 8.27104663848877
Epoch 7, Loss: 5.033824920654297
Epoch 8, Loss: 2.385737895965576
Epoch 9, Loss: 0.8384689092636108
Epoch 10, Loss: 0.2522497773170471
Training complete.


## Step 5: Training the Ridge Regression Model

In [ ]:
from cuml.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)
encoded_sequences_flattened = [seq.flatten() for seq in encoded_sequences]
ridge_model.fit(encoded_sequences_flattened, targets)
predictions = ridge_model.predict(encoded_sequences_flattened)
mse = np.mean((predictions - targets) ** 2)
print(f'Ridge Regression MSE: {mse}')

In [ ]:
import numpy as np
import cupy as cp
from cuml.linear_model import Ridge

# Simplified dataset for testing
encoded_sequences_flattened = np.array([seq.flatten()[:100] for seq in seq_db.sequences])

# Converting numpy arrays to cupy arrays for GPU processing
encoded_sequences_flattened = cp.asarray(encoded_sequences_flattened, dtype=cp.float32)
targets = cp.asarray(seq_db.targets, dtype=cp.float32)

# Checking the shapes and data types
print("Encoded sequences shape:", encoded_sequences_flattened.shape)
print("Encoded sequences dtype:", encoded_sequences_flattened.dtype)
print("Targets shape:", targets.shape)
print("Targets dtype:", targets.dtype)

# Initializing the Ridge Regression model
ridge_model = Ridge(alpha=1.0)

# Fitting the model
try:
    ridge_model.fit(encoded_sequences_flattened, targets)
except Exception as e:
    print("Error during fitting:", e)

# Predicting the targets
try:
    predictions = ridge_model.predict(encoded_sequences_flattened)
    predictions = cp.asnumpy(predictions)
    targets = cp.asnumpy(targets)

    # Calculating the Mean Squared Error (MSE)
    mse = np.mean((predictions - targets) ** 2)
    print(f'Ridge Regression MSE: {mse}')
except Exception as e:
    print("Error during prediction:", e)
