## Step 1: Load the Sequence Database 

In [16]:
import os
print(os.getcwd())

/Users/mczeneszew/Desktop/FLIPv3/examples/notebooks


In [17]:
import sys
import os
import pandas as pd

root_dir = os.path.abspath(os.path.join(os.getcwd(), '../..'))
sys.path.append(root_dir)

helpers_path = os.path.join(root_dir, 'helpers')
if not os.path.exists(helpers_path):
    raise FileNotFoundError(f"Helpers directory not found at: {helpers_path}")

from flip.utils.sequence_database import SequenceDatabase, read_csv_to_sequencedatabase

# CSV File Path 
csv_path = '../data/four_mutations_small.csv'

# Loading the sequence database from the CSV file
seq_db = read_csv_to_sequencedatabase(csv_path)

# Displaying the loaded sequence database as a DataFrame
display(seq_db.to_dataframe())

sequence    target    set  \
0  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.000000   test   
1  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.445905   test   
2  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.690164   test   
3  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.170550   test   
4  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  2.401243   test   
5  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.838187   test   
6  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.372949   test   
7  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  1.413936   test   
8  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  0.820788  train   
9  [[-1.0, -1.0, -3.0, -2.0, 0.0, -3.0, -2.0, 1.0...  0.585649  train   

  validation  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
5        NaN  
6        NaN  
7        NaN  
8        NaN  
9       True

In [18]:
print("Type of seq_db.sequences:", type(seq_db.sequences))
print("First sequence in seq_db.sequences:", seq_db.sequences[0])
print("Type of first sequence:", type(seq_db.sequences[0]))

Type of seq_db.sequences: <class 'list'>
First sequence in seq_db.sequences: [[-1. -1. -3. ...  1. -1. -1.]
 [-1. -3.  0. ... -2. -2. -1.]
 [-2. -2. -3. ... -1.  2.  7.]
 ...
 [-2. -3. -1. ... -3. -2.  2.]
 [-2. -3. -1. ... -3. -2.  2.]
 [-2. -3. -1. ... -3. -2.  2.]]
Type of first sequence: <class 'numpy.ndarray'>


In [19]:
print("Encoded sequences (BLOSUM62):")
display(seq_db.sequences)

Encoded sequences (BLOSUM62):


[array([[-1., -1., -3., ...,  1., -1., -1.],
        [-1., -3.,  0., ..., -2., -2., -1.],
        [-2., -2., -3., ..., -1.,  2.,  7.],
        ...,
        [-2., -3., -1., ..., -3., -2.,  2.],
        [-2., -3., -1., ..., -3., -2.,  2.],
        [-2., -3., -1., ..., -3., -2.,  2.]]),
 array([[-1., -1., -3., ...,  1., -1., -1.],
        [-1., -3.,  0., ..., -2., -2., -1.],
        [-2., -2., -3., ..., -1.,  2.,  7.],
        ...,
        [-2., -3., -1., ..., -3., -2.,  2.],
        [-2., -3., -1., ..., -3., -2.,  2.],
        [-2., -3., -1., ..., -3., -2.,  2.]]),
 array([[-1., -1., -3., ...,  1., -1., -1.],
        [-1., -3.,  0., ..., -2., -2., -1.],
        [-2., -2., -3., ..., -1.,  2.,  7.],
        ...,
        [-2., -3., -1., ..., -3., -2.,  2.],
        [-2., -3., -1., ..., -3., -2.,  2.],
        [-2., -3., -1., ..., -3., -2.,  2.]]),
 array([[-1., -1., -3., ...,  1., -1., -1.],
        [-1., -3.,  0., ..., -2., -2., -1.],
        [-2., -2., -3., ..., -1.,  2.,  7.],
        ..

In [20]:
print("Targets:")
display(seq_db.targets)

Targets:


[1.0,
 1.4459050863,
 1.69016355375,
 1.17054988281,
 2.40124349574,
 1.83818718188,
 1.37294933339,
 1.41393590647,
 0.820788193905,
 0.585648853727]

## Step 2: Create Dataloader  

In [29]:
# import pandas as pd
# from sequence_database import SequenceDatabase, read_csv_to_sequencedatabase
# from dataloader import create_dataloader, ProteinDataset
# import numpy as np

# protein_dataset = ProteinDataset(seq_db)
# print(f"Length of ProteinDataset: {len(protein_dataset)}")
# print(f"First item in ProteinDataset: {protein_dataset[0]}")

# batch_size = 32

# # Creating the DataLoader
# dataloader = create_dataloader(protein_dataset, batch_size=batch_size)

# print("Created DataLoader:")
# # for inputs, labels in dataloader:
# #     display(inputs, labels)
# for inputs, lengths, labels in dataloader:
#     print(inputs.shape, lengths, labels)
#     break  # Only printing the first batch 

import pandas as pd
import numpy as np
import sys
import os

# Add the correct root directory to the Python path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '../..'))
sys.path.append(root_dir)

# Verify if helpers directory is accessible
helpers_path = os.path.join(root_dir, 'helpers')
if not os.path.exists(helpers_path):
    raise FileNotFoundError(f"Helpers directory not found at: {helpers_path}")

# Import the necessary modules
from flip.utils.sequence_database import SequenceDatabase, read_csv_to_sequencedatabase
from flip.utils.dataloader import create_dataloader, ProteinDataset

# Read the CSV and create SequenceDatabase
csv_path = '../data/four_mutations_small.csv'
seq_db = read_csv_to_sequencedatabase(csv_path)

# Create ProteinDataset
protein_dataset = ProteinDataset(seq_db)
print(f"Length of ProteinDataset: {len(protein_dataset)}")
print(f"First item in ProteinDataset: {protein_dataset[0]}")

# Define batch size and create DataLoader
batch_size = 32
dataloader = create_dataloader(protein_dataset, batch_size=batch_size)

print("Created DataLoader:")
# Print the first batch
for inputs, lengths, labels in dataloader:
    print(inputs.shape, lengths, labels)
    break  # Only printing the first batch 

Length of ProteinDataset: 10
First item in ProteinDataset: (tensor([[-1., -1., -3.,  ...,  1., -1., -1.],
        [-1., -3.,  0.,  ..., -2., -2., -1.],
        [-2., -2., -3.,  ..., -1.,  2.,  7.],
        ...,
        [-2., -3., -1.,  ..., -3., -2.,  2.],
        [-2., -3., -1.,  ..., -3., -2.,  2.],
        [-2., -3., -1.,  ..., -3., -2.,  2.]]), tensor(1.))
Created DataLoader:
torch.Size([10, 265, 20]) tensor([265, 265, 265, 265, 265, 265, 265, 265, 265, 265]) tensor([2.4012, 0.5856, 1.4139, 1.8382, 1.0000, 1.4459, 1.1705, 1.6902, 1.3729,
        0.8208])


## Step 4: Train the CNN Model 

In [31]:
import sys
import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd

# Check the current working directory
print("Current working directory:", os.getcwd())

# Manually add the correct root directory to the Python path
root_dir = os.path.abspath(os.path.join(os.getcwd(), '../..'))
print("Root directory to be added to Python path:", root_dir)
sys.path.append(root_dir)

# Verify if helpers directory is accessible
helpers_path = os.path.join(root_dir, 'helpers')
print("Helpers directory exists:", os.path.exists(helpers_path))

# Import the necessary modules
from flip.utils.sequence_database import SequenceDatabase, read_csv_to_sequencedatabase
from flip.utils.dataloader import create_dataloader, ProteinDataset
from flip.models.models_flip import ConvNet

# Read the CSV and create SequenceDatabase
csv_path = '../data/four_mutations_small.csv'
seq_db = read_csv_to_sequencedatabase(csv_path)

# Create ProteinDataset
protein_dataset = ProteinDataset(seq_db)
print(f"Length of ProteinDataset: {len(protein_dataset)}")
print(f"First item in ProteinDataset: {protein_dataset[0]}")

# Define batch size and create DataLoader
batch_size = 32
dataloader = create_dataloader(protein_dataset, batch_size=batch_size)

print("Created DataLoader:")
# Print the first batch
for inputs, lengths, labels in dataloader:
    print(inputs.shape, lengths, labels)
    break  # Only printing the first batch

# Model Training Script
input_size = protein_dataset[0][0].shape[0]  
sequence_length = protein_dataset[0][0].shape[1]  # Getting the sequence length from data 

cnn_model = ConvNet(input_size=input_size, sequence_length=sequence_length)

# Defining loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(cnn_model.parameters(), lr=0.001)

# Now, we can train the model
cnn_model.train()
for epoch in range(10):  # Setting number of epochs 
    for inputs, lengths, labels in dataloader:
        inputs = torch.tensor(inputs, dtype=torch.float32)
        lengths = torch.tensor(lengths, dtype=torch.float32)
        labels = torch.tensor(labels, dtype=torch.float32)
        print("Input shape:", inputs.shape)  # Debug print

        optimizer.zero_grad()
        outputs = cnn_model(inputs, lengths)
        loss = criterion(outputs, labels.unsqueeze(1))  # Ensuring labels match output shape
        loss.backward()
        optimizer.step()
    print(f'Epoch {epoch+1}, Loss: {loss.item()}')

print("Training complete.")


Current working directory: /Users/mczeneszew/Desktop/FLIPv3/examples/notebooks
Root directory to be added to Python path: /Users/mczeneszew/Desktop/FLIPv3
Helpers directory exists: True
Length of ProteinDataset: 10
First item in ProteinDataset: (tensor([[-1., -1., -3.,  ...,  1., -1., -1.],
        [-1., -3.,  0.,  ..., -2., -2., -1.],
        [-2., -2., -3.,  ..., -1.,  2.,  7.],
        ...,
        [-2., -3., -1.,  ..., -3., -2.,  2.],
        [-2., -3., -1.,  ..., -3., -2.,  2.],
        [-2., -3., -1.,  ..., -3., -2.,  2.]]), tensor(1.))
Created DataLoader:
torch.Size([10, 265, 20]) tensor([265, 265, 265, 265, 265, 265, 265, 265, 265, 265]) tensor([1.8382, 1.6902, 0.5856, 1.0000, 0.8208, 1.3729, 1.1705, 1.4139, 2.4012,
        1.4459])
Input shape: torch.Size([10, 265, 20])
Epoch 1, Loss: 2.8332607746124268
Input shape: torch.Size([10, 265, 20])
Epoch 2, Loss: 0.2508598864078522
Input shape: torch.Size([10, 265, 20])
Epoch 3, Loss: 0.3516028821468353
Input shape: torch.Size([10, 2

/var/folders/_q/32dn15tx2w90m2l4r4vkjcpc0000gp/T/ipykernel_92308/2757212411.py:89: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs = torch.tensor(inputs, dtype=torch.float32)
/var/folders/_q/32dn15tx2w90m2l4r4vkjcpc0000gp/T/ipykernel_92308/2757212411.py:90: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  lengths = torch.tensor(lengths, dtype=torch.float32)
/var/folders/_q/32dn15tx2w90m2l4r4vkjcpc0000gp/T/ipykernel_92308/2757212411.py:91: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  labels = torch.tensor(labels, dtype=torch.float32)


## Step 4.5: Training the CNN model on sequences of different lengths   

In [37]:
import sys
import os
import torch
import torch.nn as nn
import torch.optim as optim
import pandas as pd
import numpy as np

root_dir = os.path.abspath(os.path.join(os.getcwd(), '../..'))
sys.path.append(root_dir)

# Importing the necessary modules
from flip.utils.sequence_database import SequenceDatabase, read_csv_to_sequencedatabase
from flip.utils.dataloader import create_dataloader, ProteinDataset
from flip.models.models_flip import ConvNet

# Reading the CSV and creating SequenceDatabase
csv_path = '../data/four_mutations_random_lengths.csv'
seq_db = read_csv_to_sequencedatabase(csv_path)

# Creating ProteinDataset
protein_dataset = ProteinDataset(seq_db)

In [38]:
batch_size = 32
dataloader = create_dataloader(protein_dataset, batch_size=batch_size)

print("Created DataLoader:")
for inputs, lengths, labels in dataloader:
    print(inputs.shape, lengths, labels)
    break  # Only printing the first batch

# Model Training Script
input_size = protein_dataset[0][0].shape[1]  # This is the number of features per amino acid
sequence_length = max([len(seq) for seq in seq_db.sequences])  # Maximum sequence length in the dataset
cnn_model = ConvNet(input_size=input_size, sequence_length=sequence_length)

# Defining the loss function and optimizer
criterion = nn.MSELoss()
optimizer = optim.Adam(cnn_model.parameters(), lr=0.001)

# Training the model
cnn_model.train()
num_epochs = 10
for epoch in range(num_epochs):  
    epoch_loss = 0.0 
    
    for inputs, lengths, labels in dataloader:
        inputs = inputs.float().transpose(1, 2)
        labels = labels.float().unsqueeze(1)
        optimizer.zero_grad()
        outputs = cnn_model(inputs, lengths)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        epoch_loss += loss.item()
    
    average_loss = epoch_loss / len(dataloader)
    print(f'Epoch {epoch+1}/{num_epochs}, Loss: {average_loss}')

print("Training complete.")

Created DataLoader:
torch.Size([10, 263, 20]) tensor([255, 258, 255, 255, 261, 259, 263, 260, 257, 256]) tensor([0.5856, 1.1705, 1.6902, 2.4012, 0.8208, 1.4139, 1.3729, 1.4459, 1.8382,
        1.0000])
Epoch 1/10, Loss: 2.194927930831909
Epoch 2/10, Loss: 766.2628173828125
Epoch 3/10, Loss: 21.116275787353516
Epoch 4/10, Loss: 4.276553153991699
Epoch 5/10, Loss: 3.6542675495147705
Epoch 6/10, Loss: 3.2011959552764893
Epoch 7/10, Loss: 2.6982626914978027
Epoch 8/10, Loss: 2.1052613258361816
Epoch 9/10, Loss: 1.2481050491333008
Epoch 10/10, Loss: 0.5172885060310364
Training complete.


## Step 5: Training the Ridge Regression Model

In [ ]:
from cuml.linear_model import Ridge

ridge_model = Ridge(alpha=1.0)
encoded_sequences_flattened = [seq.flatten() for seq in encoded_sequences]
ridge_model.fit(encoded_sequences_flattened, targets)
predictions = ridge_model.predict(encoded_sequences_flattened)
mse = np.mean((predictions - targets) ** 2)
print(f'Ridge Regression MSE: {mse}')

: 

In [ ]:
import numpy as np
import cupy as cp
from cuml.linear_model import Ridge

# Simplified dataset for testing
encoded_sequences_flattened = np.array([seq.flatten()[:100] for seq in seq_db.sequences])

# Converting numpy arrays to cupy arrays for GPU processing
encoded_sequences_flattened = cp.asarray(encoded_sequences_flattened, dtype=cp.float32)
targets = cp.asarray(seq_db.targets, dtype=cp.float32)

# Checking the shapes and data types
print("Encoded sequences shape:", encoded_sequences_flattened.shape)
print("Encoded sequences dtype:", encoded_sequences_flattened.dtype)
print("Targets shape:", targets.shape)
print("Targets dtype:", targets.dtype)

# Initializing the Ridge Regression model
ridge_model = Ridge(alpha=1.0)

# Fitting the model
try:
    ridge_model.fit(encoded_sequences_flattened, targets)
except Exception as e:
    print("Error during fitting:", e)

# Predicting the targets
try:
    predictions = ridge_model.predict(encoded_sequences_flattened)
    predictions = cp.asnumpy(predictions)
    targets = cp.asnumpy(targets)

    # Calculating the Mean Squared Error (MSE)
    mse = np.mean((predictions - targets) ** 2)
    print(f'Ridge Regression MSE: {mse}')
except Exception as e:
    print("Error during prediction:", e)


: 